// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDhQMQdU5H4iF4tfE0HrE2wfpvPOwRmMg',
    appId: '1:367746170477:web:cae368a77f4da2e7ca0964',
    messagingSenderId: '367746170477',
    projectId: 'fir-tutorial-3e867',
    authDomain: 'fir-tutorial-3e867.firebaseapp.com',
    storageBucket: 'fir-tutorial-3e867.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjkax6r0Q8wMCXztSmU1j-YZK8LF5ctuQ',
    appId: '1:367746170477:android:5d55892a94f7f79fca0964',
    messagingSenderId: '367746170477',
    projectId: 'fir-tutorial-3e867',
    storageBucket: 'fir-tutorial-3e867.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFw7sIhUOQBBkQzySEmn8-USUjKadcLqs',
    appId: '1:367746170477:ios:e6017c42e5a7b643ca0964',
    messagingSenderId: '367746170477',
    projectId: 'fir-tutorial-3e867',
    storageBucket: 'fir-tutorial-3e867.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFw7sIhUOQBBkQzySEmn8-USUjKadcLqs',
    appId: '1:367746170477:ios:e6017c42e5a7b643ca0964',
    messagingSenderId: '367746170477',
    projectId: 'fir-tutorial-3e867',
    storageBucket: 'fir-tutorial-3e867.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDhQMQdU5H4iF4tfE0HrE2wfpvPOwRmMg',
    appId: '1:367746170477:web:bfb04ccc33261773ca0964',
    messagingSenderId: '367746170477',
    projectId: 'fir-tutorial-3e867',
    authDomain: 'fir-tutorial-3e867.firebaseapp.com',
    storageBucket: 'fir-tutorial-3e867.firebasestorage.app',
  );
}
